// Data-driven piece-type definitions consumed by src/lib/engine.ts.
//
// Every visible sign-type sheet in the blank workbook maps to one entry here.
// Formulas are transcribed from docs/17-estimating-piece-formulas.md (which is
// auto-generated by scripts/dump-piece-formulas.py from the blank workbook).
//
// The four formulas explicitly anchored in docs/16-estimating.md are
// "verified" types with covering unit tests in src/__tests__/engine.test.ts.
// The rest are "implemented-from-workbook" types — their math follows the
// workbook formulas as faithfully as possible, but only spot-tested. Anything
// that's genuinely ambiguous in the workbook is flagged with a // TODO and a
// cell reference, per the build spec.

import { RATES, TABLES, tierFor, type RateTier } from './rates';

// ---------------------------------------------------------------------------
// Shapes
// ---------------------------------------------------------------------------

export type InputKind = 'number' | 'integer' | 'text' | 'select';

export interface InputDef {
  readonly key: string;
  readonly label: string;
  readonly kind: InputKind;
  readonly default?: number | string;
  readonly min?: number;
  readonly max?: number;
  readonly options?: readonly { value: string; label: string }[];
  readonly unit?: string;
  readonly help?: string;
}

export interface ComputedLaborLine {
  readonly workCode: number;
  readonly description?: string;
  readonly hours: number;
}

export interface ComputedMaterialLine {
  readonly itemNo: string;
  readonly description?: string;
  readonly units: number;
  readonly unitPrice?: number;
  readonly unitCost?: number;
  readonly profitPct?: number;
}

export interface ComputedPiece {
  readonly sqft: number;
  readonly labor: readonly ComputedLaborLine[];
  readonly materials: readonly ComputedMaterialLine[];
  readonly notes?: readonly string[];
}

export type PieceCompute = (inputs: Record<string, number | string>) => ComputedPiece;

export interface PieceTypeDef {
  readonly id: string;
  readonly label: string;
  readonly workbookSheet: string;
  readonly status: 'verified' | 'implemented' | 'todo';
  readonly inputs: readonly InputDef[];
  readonly compute: PieceCompute;
  readonly references?: readonly string[];
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** CEILING(x, step) — round x up to the nearest multiple of step.
 *  Mirrors Excel's CEILING(value, significance). */
export function ceilingMultiple(x: number, step: number): number {
  if (step <= 0) return x;
  if (x <= 0) return 0;
  return Math.ceil(x / step) * step;
}

/** CEILING(value / rate, B84). B84 is RATES.hourRoundingFactor = 0.25. */
function laborHours(units: number, ratePerHour: number): number {
  if (units <= 0 || ratePerHour <= 0) return 0;
  return ceilingMultiple(units / ratePerHour, RATES.hourRoundingFactor);
}

function num(inputs: Record<string, number | string>, key: string, fallback = 0): number {
  const v = inputs[key];
  if (typeof v === 'number' && Number.isFinite(v)) return v;
  if (typeof v === 'string' && v.trim() !== '') {
    const n = Number(v);
    if (Number.isFinite(n)) return n;
  }
  return fallback;
}

function str(inputs: Record<string, number | string>, key: string, fallback = ''): string {
  const v = inputs[key];
  return typeof v === 'string' ? v : fallback;
}

const COMMON_HW = {
  H: { key: 'H', label: 'Height', kind: 'number' as const, unit: 'in', min: 0 },
  L: { key: 'L', label: 'Length', kind: 'number' as const, unit: 'in', min: 0 },
  D: { key: 'D', label: 'Depth', kind: 'number' as const, unit: 'in', min: 0 },
  qty: { key: 'qty', label: 'Quantity', kind: 'integer' as const, default: 1, min: 1 },
};

const SHAPE_OPTIONS = [
  { value: 'Rectangular', label: 'Rectangular' },
  { value: 'Radius/Angle', label: 'Radius/Angle' },
] as const;

const PUSH_THROUGH_OPTIONS = [
  { value: 'No', label: 'No' },
  { value: 'Yes', label: 'Yes' },
] as const;

const LED_FAMILY_OPTIONS = [
  { value: 'synergy', label: 'Synergy 24V (1.3 LEDs/sqft, 108 LEDs/PSU)' },
  { value: 'quickmod', label: 'Quickmod 12V (1.5 LEDs/sqft, 50 LEDs/PSU)' },
] as const;

// Auto-applied EST PAINT - CUSTOM material line. The catalog price is
// $0.051/unit (gram). For extra paint colors we apply
// units = paint_area_sqft * grams_per_sqft * extraColors * extraPaintPct
// per the workbook's "extra paint color materials" formula
// (=B5*F46*B57*B49 in Post-and-panel etc.).
function extraPaintMaterial(extraColors: number, paintAreaSqft: number): ComputedMaterialLine | null {
  if (extraColors <= 0 || paintAreaSqft <= 0) return null;
  const grams = Math.round(
    paintAreaSqft * RATES.paintGramsPerSqft * RATES.extraPaintColorPct * extraColors
  );
  if (grams <= 0) return null;
  return {
    itemNo: 'EST PAINT - CUSTOM',
    description: 'Estimate for Custom Paint Color',
    units: grams,
    unitCost: 0.02856,
    unitPrice: 0.051,
    profitPct: 44.45,
  };
}

// ---------------------------------------------------------------------------
// VERIFIED piece types (formulas anchored in docs/16-estimating.md)
// ---------------------------------------------------------------------------

const FREEFORM_TM: PieceTypeDef = {
  id: 'freeform-tm',
  label: 'Freeform time & material',
  workbookSheet: 'Freeform time and material',
  status: 'verified',
  references: ['Pure user-entered material + labor lines.'],
  inputs: [{ key: 'description', label: 'Description', kind: 'text', default: '' }],
  compute: () => ({ sqft: 0, labor: [], materials: [] }),
};

const APPLY_VINYL_GRAPHICS: PieceTypeDef = {
  id: 'apply-vinyl-graphics',
  label: 'Apply vinyl graphics',
  workbookSheet: 'Apply vinyl graphics',
  status: 'verified',
  references: ['B6 qty, B7 H, B8 L; sqft=B46=(B7*B8/144)*B6; labor 2416 hrs ceil(sqft/(32|15), 0.5)'],
  inputs: [
    COMMON_HW.H,
    COMMON_HW.L,
    COMMON_HW.qty,
    {
      key: 'surface',
      label: 'Surface',
      kind: 'select',
      default: 'flat',
      options: [
        { value: 'flat', label: 'Flat (32 sqft/hr)' },
        { value: 'push-through', label: 'Push-through (15 sqft/hr)' },
      ],
    },
  ],
  compute: (inputs) => {
    const H = num(inputs, 'H');
    const L = num(inputs, 'L');
    const qty = Math.max(1, Math.round(num(inputs, 'qty', 1)));
    const surface = str(inputs, 'surface', 'flat');
    const sqft = (H * L / 144) * qty;
    const rate = surface === 'push-through'
      ? RATES.vinylApplyPushThroughSqftPerHour
      : RATES.vinylApplyFlatSqftPerHour;
    const hours = sqft > 0 ? ceilingMultiple(sqft / rate, 0.5) : 0;
    return {
      sqft,
      labor: [{ workCode: 2416, hours }],
      materials: [],
    };
  },
};

const VINYL_CUTTING: PieceTypeDef = {
  id: 'vinyl-cutting',
  label: 'Vinyl cutting',
  workbookSheet: 'Vinyl cutting',
  status: 'verified',
  references: ['B6 qty, B7 H, B8 L; sqft=B46=CEILING((B7*B8)/144,4)*B6; labor 2415 hrs ceil(sqft/20, 0.25)'],
  inputs: [COMMON_HW.H, COMMON_HW.L, COMMON_HW.qty],
  compute: (inputs) => {
    const H = num(inputs, 'H');
    const L = num(inputs, 'L');
    const qty = Math.max(1, Math.round(num(inputs, 'qty', 1)));
    const sqftRaw = (H * L) / 144;
    const sqft = sqftRaw > 0 ? ceilingMultiple(sqftRaw, 4) * qty : 0;
    return {
      sqft,
      labor: [{ workCode: 2415, hours: laborHours(sqft, RATES.vinylCutSqftPerHour) }],
      materials: [],
    };
  },
};

const PAINT_CALCULATION: PieceTypeDef = {
  id: 'paint-calculation',
  label: 'Paint calculation',
  workbookSheet: 'Paint calculation',
  status: 'verified',
  references: ['sqft=(H*L/144)*faces; paint grams=ROUND(sqft*100); 2110=sqft/20; 2112=sqft/25'],
  inputs: [
    COMMON_HW.H,
    COMMON_HW.L,
    { key: 'faces', label: 'Faces', kind: 'integer', default: 1, min: 1 },
  ],
  compute: (inputs) => {
    const H = num(inputs, 'H');
    const L = num(inputs, 'L');
    const faces = Math.max(1, Math.round(num(inputs, 'faces', 1)));
    const sqft = (H * L / 144) * faces;
    const grams = sqft > 0 ? Math.round(sqft * RATES.paintGramsPerSqft) : 0;
    return {
      sqft,
      labor: [
        { workCode: 2110, hours: sqft / 20 },
        { workCode: 2112, hours: sqft / 25 },
      ],
      materials: grams > 0
        ? [{
            itemNo: 'EST PAINT - CUSTOM',
            description: 'Estimate for Custom Paint Color',
            units: grams,
            unitCost: 0.02856,
            unitPrice: 0.051,
            profitPct: 44.45,
          }]
        : [],
    };
  },
};

const ROUTED_PANEL_SHAPES: PieceTypeDef = {
  id: 'routed-panel-shapes',
  label: 'Routed panel shapes',
  workbookSheet: 'Routed panel shapes',
  status: 'verified',
  references: ['sqft=(H*L/144)*panels; 2010 setup 1hr + 2010 routing=sqft/50'],
  inputs: [
    COMMON_HW.H,
    COMMON_HW.L,
    { key: 'panels', label: 'Panels', kind: 'integer', default: 1, min: 1 },
  ],
  compute: (inputs) => {
    const H = num(inputs, 'H');
    const L = num(inputs, 'L');
    const panels = Math.max(1, Math.round(num(inputs, 'panels', 1)));
    const sqft = (H * L / 144) * panels;
    return {
      sqft,
      labor: [
        { workCode: 2010, description: 'Routing Labor — setup', hours: sqft > 0 ? RATES.routerSetupHours : 0 },
        { workCode: 2010, description: 'Routing Labor — panel routing', hours: sqft / RATES.routedPanelShapeSqftPerHour },
      ],
      materials: [],
    };
  },
};

// ---------------------------------------------------------------------------
// IMPLEMENTED piece types (transcribed from docs/17-estimating-piece-formulas.md)
// ---------------------------------------------------------------------------

const FLAT_PANELS_ONLY: PieceTypeDef = {
  id: 'flat-panels',
  label: 'Flat panels only',
  workbookSheet: 'Flat panels only',
  status: 'implemented',
  references: ['B33 G=IF(plastic, ceil(E33/F33,B84); B34 G=IF(metal, ceil(E34/F34,B84)'],
  inputs: [
    COMMON_HW.H, COMMON_HW.L,
    { key: 'panels', label: 'Number of panels', kind: 'integer', default: 1, min: 1 },
    {
      key: 'material',
      label: 'Panel material',
      kind: 'select',
      default: 'Acrylic',
      options: [
        { value: 'Acrylic', label: 'Acrylic (72 sqft/hr)' },
        { value: 'Polycarbonate', label: 'Polycarbonate (48 sqft/hr)' },
        { value: 'ACM', label: 'ACM (96 sqft/hr)' },
        { value: 'Pre-Paint Aluminum', label: 'Pre-paint aluminum (96 sqft/hr)' },
      ],
    },
  ],
  compute: (inputs) => {
    const H = num(inputs, 'H');
    const L = num(inputs, 'L');
    const panels = Math.max(1, Math.round(num(inputs, 'panels', 1)));
    const material = str(inputs, 'material', 'Acrylic');
    const sqft = (H * L / 144) * panels;
    const procSqft = ceilingMultiple(sqft, 10);
    const rateByMaterial: Record<string, number> = {
      Acrylic: RATES.acrylicCutSqftPerHour,
      Polycarbonate: RATES.polycarbCutSqftPerHour,
      ACM: RATES.acmCutSqftPerHour,
      'Pre-Paint Aluminum': RATES.prepaintedAlumCutSqftPerHour,
    };
    const rate = rateByMaterial[material] ?? RATES.acrylicCutSqftPerHour;
    const isPlastic = material === 'Acrylic' || material === 'Polycarbonate';
    const labor: ComputedLaborLine[] = isPlastic
      ? [{ workCode: 2312, description: 'Plastic Face Labor', hours: laborHours(procSqft, rate) }]
      : [{ workCode: 2011, description: 'Cabinet Metal Labor', hours: laborHours(procSqft, rate) }];
    return { sqft, labor, materials: [] };
  },
};

const ROUTED_ALUM_FACES_LETTERS: PieceTypeDef = {
  id: 'routed-alum-faces-letters',
  label: 'Routed aluminum faces / letters',
  workbookSheet: 'Routed alum faces letters',
  status: 'implemented',
  references: ['sqft=B7*B8*B6/144; B49=B9*B48*B6; rate=B47=200'],
  inputs: [
    COMMON_HW.H, COMMON_HW.L, COMMON_HW.qty,
    { key: 'inchesOfCopy', label: 'Total inches of copy', kind: 'number', default: 0, min: 0, unit: 'in' },
  ],
  compute: (inputs) => {
    const H = num(inputs, 'H');
    const L = num(inputs, 'L');
    const qty = Math.max(1, Math.round(num(inputs, 'qty', 1)));
    const inchesOfCopy = num(inputs, 'inchesOfCopy');
    const sqft = (H * L * qty) / 144;
    const inches = inchesOfCopy * RATES.letterPerimeterPathFactor * qty;
    const setup = sqft > 0 ? RATES.routerSetupHours : 0;
    return {
      sqft,
      labor: [
        { workCode: 2010, description: 'Routing Labor — setup', hours: setup },
        { workCode: 2010, description: 'Routing Labor — aluminum copy', hours: laborHours(inches, RATES.routingAluminumInchesPerHour) },
      ],
      materials: [],
    };
  },
};

const ROUTED_PUSH_THROUGH_ACRYLIC: PieceTypeDef = {
  id: 'routed-push-through-acrylic',
  label: 'Routed push-through acrylic',
  workbookSheet: 'Routed push through acrylic',
  status: 'implemented',
  references: ['Identical shape to Routed alum faces letters but rate=100'],
  inputs: [
    COMMON_HW.H, COMMON_HW.L, COMMON_HW.qty,
    { key: 'inchesOfCopy', label: 'Total inches of copy', kind: 'number', default: 0, min: 0, unit: 'in' },
  ],
  compute: (inputs) => {
    const H = num(inputs, 'H');
    const L = num(inputs, 'L');
    const qty = Math.max(1, Math.round(num(inputs, 'qty', 1)));
    const inchesOfCopy = num(inputs, 'inchesOfCopy');
    const sqft = (H * L * qty) / 144;
    const inches = inchesOfCopy * RATES.letterPerimeterPathFactor * qty;
    const setup = sqft > 0 ? RATES.routerSetupHours : 0;
    return {
      sqft,
      labor: [
        { workCode: 2010, description: 'Routing Labor — setup', hours: setup },
        { workCode: 2010, description: 'Routing Labor — push-through acrylic', hours: laborHours(inches, RATES.routingPushThroughInchesPerHour) },
      ],
      materials: [],
    };
  },
};

const TRIMCAP_LETTER_FACE: PieceTypeDef = {
  id: 'trimcap-letter-face',
  label: 'Trimcap letter face',
  workbookSheet: 'Trimcap letter face',
  status: 'implemented',
  references: ['inches/21 (trimCapFaceFabInchesPerHour)'],
  inputs: [
    { key: 'inches', label: 'Letter perimeter inches', kind: 'number', default: 0, min: 0, unit: 'in' },
    { key: 'qty', label: 'Letters', kind: 'integer', default: 1, min: 1 },
  ],
  compute: (inputs) => {
    const inches = num(inputs, 'inches');
    const qty = Math.max(1, Math.round(num(inputs, 'qty', 1)));
    const total = inches * qty;
    return {
      sqft: 0,
      labor: [{ workCode: 2314, description: 'Plastic Letter Face Labor', hours: laborHours(total, RATES.trimCapFaceFabInchesPerHour) }],
      materials: [],
    };
  },
};

const CHANNEL_LETTER_FABRICATION: PieceTypeDef = {
  id: 'channel-letter-fabrication',
  label: 'Channel letter fabrication',
  workbookSheet: 'Channel letter fabrication',
  status: 'implemented',
  references: ['inches/(block 18|serif 12|script 8); WC 2014'],
  inputs: [
    { key: 'inches', label: 'Letter perimeter inches', kind: 'number', default: 0, min: 0, unit: 'in' },
    { key: 'qty', label: 'Letters', kind: 'integer', default: 1, min: 1 },
    {
      key: 'face',
      label: 'Typeface',
      kind: 'select',
      default: 'block',
      options: [
        { value: 'block', label: 'Block (18 in/hr)' },
        { value: 'serif', label: 'Serif (12 in/hr)' },
        { value: 'script', label: 'Script (8 in/hr)' },
      ],
    },
  ],
  compute: (inputs) => {
    const inches = num(inputs, 'inches');
    const qty = Math.max(1, Math.round(num(inputs, 'qty', 1)));
    const face = str(inputs, 'face', 'block');
    const rate = face === 'serif'
      ? RATES.channelLetterSerifFabInchesPerHour
      : face === 'script'
        ? RATES.channelLetterScriptFabInchesPerHour
        : RATES.channelLetterBlockFabInchesPerHour;
    const total = inches * qty;
    return {
      sqft: 0,
      labor: [{ workCode: 2014, description: `Letter Metal Labor — ${face}`, hours: laborHours(total, rate) }],
      materials: [],
    };
  },
};

const LED_WIRING: PieceTypeDef = {
  id: 'led-wiring',
  label: 'LED wiring',
  workbookSheet: 'LED wiring',
  status: 'implemented',
  references: ['Synergy: 1.3 LEDs/sqft, 108 LEDs/PSU. Quickmod: 1.5/50.'],
  inputs: [
    COMMON_HW.H, COMMON_HW.L, COMMON_HW.qty,
    {
      key: 'ledFamily',
      label: 'LED family',
      kind: 'select',
      default: 'synergy',
      options: [...LED_FAMILY_OPTIONS],
    },
  ],
  compute: (inputs) => {
    const H = num(inputs, 'H');
    const L = num(inputs, 'L');
    const qty = Math.max(1, Math.round(num(inputs, 'qty', 1)));
    const family = str(inputs, 'ledFamily', 'synergy');
    const sqft = (H * L / 144) * qty;
    const ledsPerSqft = family === 'quickmod' ? RATES.quickmodLedsPerSqft : RATES.synergyLedsPerSqft;
    const ledsPerPSU = family === 'quickmod' ? RATES.quickmodLedsPerPowerSupply : RATES.synergyLedsPerPowerSupply;
    const leds = Math.ceil(sqft * ledsPerSqft);
    const psus = leds > 0 ? Math.ceil(leds / ledsPerPSU) : 0;
    return {
      sqft,
      labor: [{ workCode: 2212, description: 'LED Wiring Labor', hours: laborHours(sqft, RATES.ledWiringSqftPerHour) }],
      materials: [
        { itemNo: `LED-${family}`, description: `${family === 'quickmod' ? 'Quickmod 12V' : 'Synergy 24V'} LEDs`, units: leds, unitPrice: 0, unitCost: 0, profitPct: 0 },
        { itemNo: `PSU-${family}`, description: `${family === 'quickmod' ? 'Quickmod 12V' : 'Synergy 24V'} Power Supply`, units: psus, unitPrice: 0, unitCost: 0, profitPct: 0 },
      ],
    };
  },
};

const CRATING: PieceTypeDef = {
  id: 'crating',
  label: 'Crating',
  workbookSheet: 'Crating',
  status: 'implemented',
  references: ['Hand-entered hours on WC 2216 Crating Labor.'],
  inputs: [
    { key: 'description', label: 'Description', kind: 'text', default: '' },
    { key: 'hours', label: 'Estimated hours (2216)', kind: 'number', default: 0, min: 0, unit: 'hr' },
  ],
  compute: (inputs) => {
    const hours = num(inputs, 'hours');
    return {
      sqft: 0,
      labor: hours > 0 ? [{ workCode: 2216, description: 'Crating Labor', hours }] : [],
      materials: [],
    };
  },
};

const STRUCTURAL_STEEL_FAB: PieceTypeDef = {
  id: 'structural-steel',
  label: 'Structural steel fabrication',
  workbookSheet: 'Structural Steel Fab',
  status: 'implemented',
  references: ['Hand-entered hours on WC 2016.'],
  inputs: [
    { key: 'description', label: 'Description', kind: 'text', default: '' },
    { key: 'hours', label: 'Estimated hours (2016)', kind: 'number', default: 0, min: 0, unit: 'hr' },
  ],
  compute: (inputs) => {
    const hours = num(inputs, 'hours');
    return {
      sqft: 0,
      labor: hours > 0 ? [{ workCode: 2016, description: 'Structural Steel Metal Labor', hours }] : [],
      materials: [],
    };
  },
};

const REVEAL: PieceTypeDef = {
  id: 'reveal',
  label: 'Reveal',
  workbookSheet: 'Reveal',
  status: 'implemented',
  references: ['TABLES.reveal; paintPrep/paint at revealPaintPrepSqftPerHour (15)'],
  inputs: [COMMON_HW.H, COMMON_HW.L, COMMON_HW.qty],
  compute: (inputs) => {
    const H = num(inputs, 'H');
    const L = num(inputs, 'L');
    const qty = Math.max(1, Math.round(num(inputs, 'qty', 1)));
    const sqft = (H * L / 144) * qty;
    const fabRate = tierFor(TABLES.reveal, sqft);
    return {
      sqft,
      labor: [
        { workCode: 2011, description: 'Cabinet Metal Labor', hours: laborHours(sqft, fabRate) },
        { workCode: 2110, description: 'Paint Prep Labor', hours: laborHours(sqft, RATES.revealPaintPrepSqftPerHour) },
        { workCode: 2112, description: 'Paint Cabinet & Letters Labor', hours: laborHours(sqft, RATES.revealPaintSqftPerHour) },
      ],
      materials: [],
    };
  },
};

const CROWN_COVE: PieceTypeDef = {
  id: 'crown-cove',
  label: 'Crown cove top',
  workbookSheet: 'Crown cove top',
  status: 'implemented',
  references: ['TABLES.crown; crownPaintPrep (6), crownPaint (15)'],
  inputs: [COMMON_HW.H, COMMON_HW.L, COMMON_HW.qty],
  compute: (inputs) => {
    const H = num(inputs, 'H');
    const L = num(inputs, 'L');
    const qty = Math.max(1, Math.round(num(inputs, 'qty', 1)));
    const sqft = (H * L / 144) * qty;
    const fabRate = tierFor(TABLES.crown, sqft);
    return {
      sqft,
      labor: [
        { workCode: 2011, description: 'Cabinet Metal Labor', hours: laborHours(sqft, fabRate) },
        { workCode: 2110, description: 'Paint Prep (bondo)', hours: laborHours(sqft, RATES.crownPaintPrepSqftPerHour) },
        { workCode: 2112, description: 'Paint', hours: laborHours(sqft, RATES.crownPaintSqftPerHour) },
      ],
      materials: [],
    };
  },
};

const CHANGEABLE_COPY_FACE: PieceTypeDef = {
  id: 'changeable-copy-face',
  label: 'Changeable copy face',
  workbookSheet: 'Changeable copy face',
  status: 'implemented',
  references: ['ccRailFabFtPerHour 16; dividerBarFtPerHour 8'],
  inputs: [
    COMMON_HW.H, COMMON_HW.L, COMMON_HW.qty,
    { key: 'rows', label: 'Rows of divider bar', kind: 'integer', default: 0, min: 0 },
  ],
  compute: (inputs) => {
    const H = num(inputs, 'H');
    const L = num(inputs, 'L');
    const qty = Math.max(1, Math.round(num(inputs, 'qty', 1)));
    const rows = Math.max(0, Math.round(num(inputs, 'rows', 0)));
    const sqft = (H * L / 144) * qty;
    const perimeterFt = (((H + L) * 2) / 12) * qty;
    const dividerFt = (rows * L) / 12 * qty;
    return {
      sqft,
      labor: [
        { workCode: 2011, description: 'CC rail fabrication', hours: laborHours(perimeterFt, RATES.ccRailFabFtPerHour) },
        { workCode: 2011, description: 'Divider bar labor', hours: laborHours(dividerFt, RATES.dividerBarFtPerHour) },
      ],
      materials: [],
    };
  },
};

const FLEX_FACE_ASSEMBLY: PieceTypeDef = {
  id: 'flex-face-assembly',
  label: 'Flex face assembly',
  workbookSheet: 'Flex face assembly',
  status: 'implemented',
  references: ['flexFaceAssemblySqftPerHour 15; clip ft from input.'],
  inputs: [
    COMMON_HW.H, COMMON_HW.L, COMMON_HW.qty,
    { key: 'clipFt', label: 'Clip feet (optional)', kind: 'number', default: 0, min: 0, unit: 'ft' },
    {
      key: 'clipType',
      label: 'Clip type',
      kind: 'select',
      default: 'plastic',
      options: [
        { value: 'plastic', label: 'Plastic ($2.00/ft)' },
        { value: 'metal', label: 'Metal ($1.34/ft)' },
      ],
    },
  ],
  compute: (inputs) => {
    const H = num(inputs, 'H');
    const L = num(inputs, 'L');
    const qty = Math.max(1, Math.round(num(inputs, 'qty', 1)));
    const sqft = (H * L / 144) * qty;
    const clipFt = num(inputs, 'clipFt');
    const clipType = str(inputs, 'clipType', 'plastic');
    return {
      sqft,
      labor: [{ workCode: 2316, description: 'Flex Face Assembly Labor', hours: laborHours(sqft, RATES.flexFaceAssemblySqftPerHour) }],
      materials: clipFt > 0
        ? [{
            itemNo: clipType === 'metal' ? 'FLEX-CLIP-METAL' : 'FLEX-CLIP-PLASTIC',
            description: `Flex face ${clipType} clips`,
            units: clipFt,
            unitPrice: clipType === 'metal' ? RATES.flexFaceMetalClipPerFoot : RATES.flexFaceClipPlasticPerFoot,
            unitCost: 0,
            profitPct: 0,
          }]
        : [],
    };
  },
};

const ROUTED_FACE_ASSEMBLY: PieceTypeDef = {
  id: 'routed-face-assembly',
  label: 'Routed face assembly',
  workbookSheet: 'Routed face assembly',
  status: 'implemented',
  references: ['routedBackerAssemblySqftPerHour 15; retainerAssemblySqftPerHour 40 (per ft)'],
  inputs: [COMMON_HW.H, COMMON_HW.L, COMMON_HW.qty],
  compute: (inputs) => {
    const H = num(inputs, 'H');
    const L = num(inputs, 'L');
    const qty = Math.max(1, Math.round(num(inputs, 'qty', 1)));
    const sqft = (H * L / 144) * qty;
    const perimeterFt = (((H + L) * 2) / 12) * qty;
    return {
      sqft,
      labor: [
        { workCode: 2215, description: 'Backer assembly', hours: laborHours(sqft, RATES.routedBackerAssemblySqftPerHour) },
        { workCode: 2215, description: 'Retainer assembly', hours: laborHours(perimeterFt, RATES.retainerAssemblySqftPerHour) },
      ],
      materials: [],
    };
  },
};

const ROUTED_FACE_ONLY: PieceTypeDef = {
  id: 'routed-face-only',
  label: 'Routed face only',
  workbookSheet: 'Routed face only',
  status: 'implemented',
  references: ['Multi-labor: setup, copy rout, backer rout, paint prep/paint, face fab, assembly'],
  inputs: [
    { key: 'qty', label: 'Number of faces', kind: 'integer', default: 1, min: 1 },
    COMMON_HW.H, COMMON_HW.L,
    { key: 'D', label: 'Depth', kind: 'number', default: 1, min: 0, unit: 'in' },
    { key: 'inchesOfCopy', label: 'Inches of copy', kind: 'number', default: 0, min: 0, unit: 'in' },
    {
      key: 'pushThrough',
      label: 'Push-through copy?',
      kind: 'select', default: 'No', options: [...PUSH_THROUGH_OPTIONS],
    },
  ],
  compute: (inputs) => {
    const H = num(inputs, 'H');
    const L = num(inputs, 'L');
    const faces = Math.max(1, Math.round(num(inputs, 'qty', 1)));
    const D = num(inputs, 'D');
    const inchesOfCopy = num(inputs, 'inchesOfCopy');
    const pushThrough = str(inputs, 'pushThrough', 'No').toLowerCase() === 'yes';
    const sqft = (H * L / 144) * faces;
    const perimeterFt = ((H + L * 2) / 12) * faces;
    const fillerSqft = (D / 12) * perimeterFt;
    const paintArea = fillerSqft + sqft;
    const copyInches = inchesOfCopy * RATES.letterPerimeterPathFactor * faces;
    return {
      sqft,
      labor: [
        { workCode: 2010, description: 'Routing setup', hours: sqft > 0 ? RATES.routerSetupHours : 0 },
        { workCode: 2010, description: 'Aluminum copy routing', hours: laborHours(copyInches, RATES.routingAluminumInchesPerHour) },
        { workCode: 2010, description: 'Acrylic backer routing', hours: pushThrough ? 0 : laborHours(sqft, RATES.routedPanelShapeSqftPerHour) },
        { workCode: 2010, description: 'Push-through routing', hours: pushThrough ? laborHours(copyInches, RATES.routingPushThroughInchesPerHour) : 0 },
        { workCode: 2011, description: 'Cabinet Metal Labor', hours: laborHours(sqft, RATES.routedFaceFabricationSqftPerHour) },
        { workCode: 2110, description: 'Paint Prep Labor', hours: laborHours(paintArea, RATES.cabinetPaintPrepSqftPerHour) },
        { workCode: 2112, description: 'Paint Cabinet & Letters Labor', hours: laborHours(paintArea, RATES.cabinetPaintSqftPerHour) },
        { workCode: 2313, description: 'Routed pop stud labor', hours: laborHours(sqft, RATES.routedPopStudSqftPerHour) },
        { workCode: 2215, description: 'Routed backer assembly', hours: laborHours(sqft, RATES.routedBackerAssemblySqftPerHour) },
      ],
      materials: [],
    };
  },
};

// ---------------------------------------------------------------------------
// Pan / cabinet pattern — common helper for the multi-labor sheets.
// ---------------------------------------------------------------------------

const ALUM_PAN_SIGN: PieceTypeDef = {
  id: 'alum-pan-sign',
  label: 'Aluminum pan sign',
  workbookSheet: 'Alum pan sign',
  status: 'implemented',
  references: ['TABLES.pan; panPaintPrep 43.75; panPaint 28.5; +radius/angle +extra colors'],
  inputs: [
    { key: 'shape', label: 'Shape', kind: 'select', default: 'Rectangular', options: [...SHAPE_OPTIONS] },
    { key: 'extraColors', label: 'Extra paint colors', kind: 'integer', default: 0, min: 0 },
    { key: 'qty', label: 'Number of pans', kind: 'integer', default: 1, min: 1 },
    COMMON_HW.H, COMMON_HW.L,
    { key: 'D', label: 'Depth', kind: 'number', default: 2, min: 0, unit: 'in' },
  ],
  compute: (inputs) => {
    const H = num(inputs, 'H');
    const L = num(inputs, 'L');
    const qty = Math.max(1, Math.round(num(inputs, 'qty', 1)));
    const D = num(inputs, 'D');
    const shape = str(inputs, 'shape', 'Rectangular');
    const extraColors = Math.max(0, Math.round(num(inputs, 'extraColors', 0)));
    const sqft = (H * L / 144) * qty;
    const perimeterFt = (((H + L) * 2) / 12) * qty;
    const fillerSqft = (D / 12) * perimeterFt;
    const paintArea = sqft + fillerSqft;
    const fabRate = tierFor(TABLES.pan, sqft);
    const fabHours = laborHours(sqft, fabRate);
    const radiusHours = shape === 'Radius/Angle' ? fabHours * RATES.radiusOrAngleExtraLaborPct : 0;
    const labor: ComputedLaborLine[] = [
      { workCode: 2011, description: 'Cabinet Metal Labor', hours: fabHours },
      { workCode: 2110, description: 'Paint Prep Labor', hours: laborHours(paintArea, RATES.panPaintPrepSqftPerHour) },
      { workCode: 2112, description: 'Paint Cabinet & Letters Labor', hours: laborHours(paintArea, RATES.panPaintSqftPerHour) },
    ];
    if (radiusHours > 0) labor.push({ workCode: 2011, description: 'Radius/Angle uplift', hours: radiusHours });
    if (extraColors > 0 && paintArea > 0) labor.push({ workCode: 2110, description: 'Extra color masking', hours: extraColors });
    const materials: ComputedMaterialLine[] = [];
    const paint = extraPaintMaterial(extraColors, paintArea);
    if (paint) materials.push(paint);
    return { sqft, labor, materials };
  },
};

const ECONOMY_PAN_SIGN: PieceTypeDef = {
  id: 'economy-pan-sign',
  label: 'Economy pan sign',
  workbookSheet: 'Economy pan sign',
  status: 'implemented',
  references: ['TABLES.pan; prepainted aluminum (no separate paint step)'],
  inputs: [
    { key: 'qty', label: 'Number of pans', kind: 'integer', default: 1, min: 1 },
    COMMON_HW.H, COMMON_HW.L,
    { key: 'D', label: 'Depth (2" only)', kind: 'number', default: 2, min: 0, unit: 'in' },
  ],
  compute: (inputs) => {
    const H = num(inputs, 'H');
    const L = num(inputs, 'L');
    const qty = Math.max(1, Math.round(num(inputs, 'qty', 1)));
    const sqft = (H * L / 144) * qty;
    const fabRate = tierFor(TABLES.pan, sqft);
    return {
      sqft,
      labor: [{ workCode: 2011, description: 'Cabinet Metal Labor', hours: laborHours(sqft, fabRate) }],
      materials: [],
    };
  },
};

const POST_AND_PANEL: PieceTypeDef = {
  id: 'post-and-panel',
  label: 'Post and panel sign',
  workbookSheet: 'Post and panel sign',
  status: 'implemented',
  references: ['TABLES.postAndPanel; postFabFt 24; body+post paint at 15/15'],
  inputs: [
    { key: 'shape', label: 'Shape', kind: 'select', default: 'Rectangular', options: [...SHAPE_OPTIONS] },
    { key: 'extraColors', label: 'Extra paint colors', kind: 'integer', default: 0, min: 0 },
    { key: 'qty', label: 'Number of signs', kind: 'integer', default: 1, min: 1 },
    COMMON_HW.H, COMMON_HW.L,
    { key: 'D', label: 'Depth', kind: 'number', default: 3, min: 0, unit: 'in' },
    { key: 'postCount', label: 'Number of posts', kind: 'integer', default: 0, min: 0 },
    { key: 'postLen', label: 'Length of post inches', kind: 'number', default: 0, min: 0, unit: 'in' },
  ],
  compute: (inputs) => {
    const H = num(inputs, 'H');
    const L = num(inputs, 'L');
    const qty = Math.max(1, Math.round(num(inputs, 'qty', 1)));
    const D = num(inputs, 'D');
    const shape = str(inputs, 'shape', 'Rectangular');
    const extraColors = Math.max(0, Math.round(num(inputs, 'extraColors', 0)));
    const postCount = Math.max(0, Math.round(num(inputs, 'postCount', 0)));
    const postLen = num(inputs, 'postLen');
    const sqft = (H * L / 144) * qty;
    const perimeterFt = (((H + L) * 2) / 12) * qty;
    const bodyFaceArea = sqft * 2;
    const fillerArea = (D / 12) * perimeterFt;
    const bodyPaintArea = fillerArea + bodyFaceArea;
    const postFt = (postLen * postCount / 12) * qty;
    const postPaintArea = (D / 12) * 4 * postFt;
    const totalPaintArea = bodyPaintArea + postPaintArea;
    const fabRate = tierFor(TABLES.postAndPanel, sqft);
    const bodyHours = laborHours(sqft, fabRate);
    const radiusHours = shape === 'Radius/Angle' ? bodyHours * RATES.radiusOrAngleExtraLaborPct : 0;
    const labor: ComputedLaborLine[] = [
      { workCode: 2011, description: 'Cabinet Metal Labor — body', hours: bodyHours },
      { workCode: 2011, description: 'Cabinet Metal Labor — posts', hours: laborHours(postFt, RATES.postPanelPostFabFtPerHour) },
      { workCode: 2110, description: 'Paint Prep — body', hours: laborHours(bodyPaintArea, RATES.postPanelPaintPrepSqftPerHour) },
      { workCode: 2112, description: 'Paint Cabinet & Letters — body', hours: laborHours(bodyPaintArea, RATES.postPanelPaintSqftPerHour) },
      { workCode: 2110, description: 'Paint Prep — posts', hours: laborHours(postPaintArea, RATES.postPanelPaintPrepSqftPerHour) },
      { workCode: 2112, description: 'Paint Cabinet & Letters — posts', hours: laborHours(postPaintArea, RATES.postPanelPaintSqftPerHour) },
    ];
    if (radiusHours > 0) labor.push({ workCode: 2011, description: 'Radius/Angle uplift', hours: radiusHours });
    if (extraColors > 0 && totalPaintArea > 0) labor.push({ workCode: 2110, description: 'Extra color masking', hours: extraColors });
    const materials: ComputedMaterialLine[] = [];
    const paint = extraPaintMaterial(extraColors, totalPaintArea);
    if (paint) materials.push(paint);
    return { sqft, labor, materials };
  },
};

interface CabinetOptions {
  readonly fabTable: readonly RateTier[];
  readonly fabWorkCode?: number;
  readonly facePaintMultiplier: 1 | 2;
  readonly routed?: boolean;
  readonly acrylic?: boolean;
  readonly flex?: boolean;
}

function cabinetCompute(inputs: Record<string, number | string>, opts: CabinetOptions): ComputedPiece {
  const H = num(inputs, 'H');
  const L = num(inputs, 'L');
  const qty = Math.max(1, Math.round(num(inputs, 'qty', 1)));
  const D = num(inputs, 'D');
  const shape = str(inputs, 'shape', 'Rectangular');
  const extraColors = Math.max(0, Math.round(num(inputs, 'extraColors', 0)));
  const inchesOfCopy = num(inputs, 'inchesOfCopy', 0);
  const pushThrough = str(inputs, 'pushThrough', 'No').toLowerCase() === 'yes';
  const dividerRows = Math.max(0, Math.round(num(inputs, 'dividerRows', 0)));
  const faces = opts.facePaintMultiplier;
  const sqft = (H * L / 144) * qty;
  const perimeterFt = (((H + L) * 2) / 12) * qty;
  const faceSqft = sqft * faces;
  const fillerSqft = (D / 12) * perimeterFt;
  const paintArea = faceSqft + fillerSqft;
  const fabRate = tierFor(opts.fabTable, sqft);
  const fabHours = laborHours(sqft, fabRate);
  const radiusHours = shape === 'Radius/Angle' ? fabHours * RATES.radiusOrAngleExtraLaborPct : 0;
  const fabWC = opts.fabWorkCode ?? 2011;
  const labor: ComputedLaborLine[] = [];
  if (opts.routed) {
    const setup = sqft > 0 ? RATES.routerSetupHours * 2 : 0;
    labor.push({ workCode: 2010, description: 'Routing setup', hours: setup });
    const copyInches = inchesOfCopy * RATES.letterPerimeterPathFactor * qty;
    labor.push({ workCode: 2010, description: 'Aluminum copy routing', hours: laborHours(copyInches, RATES.routingAluminumInchesPerHour) });
    labor.push({ workCode: 2010, description: 'Acrylic backer routing', hours: pushThrough ? 0 : laborHours(sqft, RATES.routedPanelShapeSqftPerHour) });
    labor.push({ workCode: 2010, description: 'Push-through routing', hours: pushThrough ? laborHours(copyInches, RATES.routingPushThroughInchesPerHour) : 0 });
  }
  labor.push({ workCode: fabWC, description: 'Cabinet Metal Labor', hours: fabHours });
  if (radiusHours > 0) labor.push({ workCode: fabWC, description: 'Radius/Angle uplift', hours: radiusHours });
  labor.push({ workCode: 2110, description: 'Paint Prep Labor', hours: laborHours(paintArea, RATES.cabinetPaintPrepSqftPerHour) });
  labor.push({ workCode: 2112, description: 'Paint Cabinet & Letters Labor', hours: laborHours(paintArea, RATES.cabinetPaintSqftPerHour) });
  labor.push({ workCode: 2212, description: 'LED Wiring Labor', hours: laborHours(faceSqft, RATES.ledWiringSqftPerHour) });
  if (opts.acrylic || opts.flex) {
    labor.push({ workCode: 2215, description: 'Assembly Labor', hours: laborHours(perimeterFt, RATES.retainerAssemblySqftPerHour) });
  } else {
    labor.push({ workCode: 2215, description: 'Assembly Labor', hours: laborHours(faceSqft, RATES.flexFaceAssemblySqftPerHour) });
  }
  if (opts.acrylic) labor.push({ workCode: 2312, description: 'Plastic Face Labor', hours: laborHours(faceSqft, RATES.acrylicCutSqftPerHour) });
  if (opts.flex) labor.push({ workCode: 2316, description: 'Flex Face Assembly Labor', hours: laborHours(faceSqft, RATES.flexFaceAssemblySqftPerHour) });
  if (opts.routed) labor.push({ workCode: 2313, description: 'Routed pop stud labor', hours: laborHours(sqft, RATES.routedPopStudSqftPerHour) });
  if (dividerRows > 0 && opts.acrylic) {
    const dividerFt = (dividerRows * L / 12) * qty;
    labor.push({ workCode: 2011, description: 'Divider bar labor', hours: laborHours(dividerFt, RATES.dividerBarFtPerHour) });
  }
  if (extraColors > 0 && paintArea > 0) labor.push({ workCode: 2110, description: 'Extra color masking', hours: extraColors });
  const materials: ComputedMaterialLine[] = [];
  const paint = extraPaintMaterial(extraColors, paintArea);
  if (paint) materials.push(paint);
  return { sqft, labor, materials };
}

function cabinetInputs(extras: readonly InputDef[] = []): readonly InputDef[] {
  return [
    { key: 'shape', label: 'Shape', kind: 'select', default: 'Rectangular', options: [...SHAPE_OPTIONS] },
    { key: 'extraColors', label: 'Extra paint colors', kind: 'integer', default: 0, min: 0 },
    { key: 'qty', label: 'Number of signs', kind: 'integer', default: 1, min: 1 },
    COMMON_HW.H, COMMON_HW.L,
    { key: 'D', label: 'Depth', kind: 'number', default: 6, min: 0, unit: 'in' },
    ...extras,
  ];
}

const SF_ROUTED_CABINET: PieceTypeDef = {
  id: 'sf-routed-cabinet', label: 'Single-face routed cabinet', workbookSheet: 'Sf routed cabinet',
  status: 'implemented', references: ['TABLES.routedCabinet; SF'],
  inputs: cabinetInputs([
    { key: 'inchesOfCopy', label: 'Inches of routed copy', kind: 'number', default: 0, min: 0, unit: 'in' },
    { key: 'pushThrough', label: 'Push-through copy?', kind: 'select', default: 'No', options: [...PUSH_THROUGH_OPTIONS] },
  ]),
  compute: (inputs) => cabinetCompute(inputs, { fabTable: TABLES.routedCabinet, facePaintMultiplier: 1, routed: true }),
};

const DF_ROUTED_CABINET: PieceTypeDef = {
  id: 'df-routed-cabinet', label: 'Double-face routed cabinet', workbookSheet: 'Df routed cabinet',
  status: 'implemented', references: ['TABLES.routedCabinet; DF'],
  inputs: cabinetInputs([
    { key: 'inchesOfCopy', label: 'Inches of routed copy (per face)', kind: 'number', default: 0, min: 0, unit: 'in' },
    { key: 'pushThrough', label: 'Push-through copy?', kind: 'select', default: 'No', options: [...PUSH_THROUGH_OPTIONS] },
  ]),
  compute: (inputs) => cabinetCompute(inputs, { fabTable: TABLES.routedCabinet, facePaintMultiplier: 2, routed: true }),
};

const SF_ACRYLIC_CABINET: PieceTypeDef = {
  id: 'sf-acrylic-cabinet', label: 'Single-face acrylic cabinet', workbookSheet: 'Sf acrylic cabinet',
  status: 'implemented', references: ['TABLES.acrylicCabinet; SF'],
  inputs: cabinetInputs([{ key: 'dividerRows', label: 'Rows of divider bar', kind: 'integer', default: 0, min: 0 }]),
  compute: (inputs) => cabinetCompute(inputs, { fabTable: TABLES.acrylicCabinet, facePaintMultiplier: 1, acrylic: true }),
};

const DF_ACRYLIC_CABINET: PieceTypeDef = {
  id: 'df-acrylic-cabinet', label: 'Double-face acrylic cabinet', workbookSheet: 'Df acrylic cabinet',
  status: 'implemented', references: ['TABLES.acrylicCabinet; DF'],
  inputs: cabinetInputs([{ key: 'dividerRows', label: 'Rows of divider bar', kind: 'integer', default: 0, min: 0 }]),
  compute: (inputs) => cabinetCompute(inputs, { fabTable: TABLES.acrylicCabinet, facePaintMultiplier: 2, acrylic: true }),
};

const ECONOMY_SF_ACRYLIC: PieceTypeDef = {
  id: 'economy-sf-acrylic', label: 'Economy SF acrylic', workbookSheet: 'Economy Sf acrylic',
  status: 'implemented', references: ['TABLES.acrylicCabinet; simplified (no paint)'],
  inputs: [
    { key: 'qty', label: 'Number of signs', kind: 'integer', default: 1, min: 1 },
    COMMON_HW.H, COMMON_HW.L,
    { key: 'D', label: 'Depth (6" only)', kind: 'number', default: 6, min: 0, unit: 'in' },
  ],
  compute: (inputs) => {
    const H = num(inputs, 'H');
    const L = num(inputs, 'L');
    const qty = Math.max(1, Math.round(num(inputs, 'qty', 1)));
    const sqft = (H * L / 144) * qty;
    const fabRate = tierFor(TABLES.acrylicCabinet, sqft);
    return {
      sqft,
      labor: [
        { workCode: 2011, description: 'Cabinet Metal Labor', hours: laborHours(sqft, fabRate) },
        { workCode: 2212, description: 'LED Wiring Labor', hours: laborHours(sqft, RATES.ledWiringSqftPerHour) },
        { workCode: 2215, description: 'Assembly Labor', hours: laborHours(sqft, RATES.retainerAssemblySqftPerHour) },
        { workCode: 2312, description: 'Plastic Face Labor', hours: laborHours(sqft, RATES.acrylicCutSqftPerHour) },
      ],
      materials: [],
    };
  },
};

const SF_FLEX_CABINET: PieceTypeDef = {
  id: 'sf-flex-cabinet', label: 'Single-face flex cabinet', workbookSheet: 'Sf flex cabinet',
  status: 'implemented', references: ['TABLES.flexCabinet; SF'],
  inputs: cabinetInputs([]),
  compute: (inputs) => cabinetCompute(inputs, { fabTable: TABLES.flexCabinet, facePaintMultiplier: 1, flex: true }),
};

const DF_FLEX_CABINET: PieceTypeDef = {
  id: 'df-flex-cabinet', label: 'Double-face flex cabinet', workbookSheet: 'Df flex cabinet',
  status: 'implemented', references: ['TABLES.flexCabinet; DF'],
  inputs: cabinetInputs([]),
  compute: (inputs) => cabinetCompute(inputs, { fabTable: TABLES.flexCabinet, facePaintMultiplier: 2, flex: true }),
};

const POLE_COVER: PieceTypeDef = {
  id: 'pole-cover',
  label: 'Pole cover',
  workbookSheet: 'Pole cover',
  status: 'implemented',
  references: ['TABLES.polecover; large-pole frame multiplier 1.3 above 61"'],
  inputs: [
    { key: 'shape', label: 'Shape', kind: 'select', default: 'Rectangular', options: [...SHAPE_OPTIONS] },
    { key: 'extraColors', label: 'Extra paint colors', kind: 'integer', default: 0, min: 0 },
    { key: 'qty', label: 'Number of polecovers', kind: 'integer', default: 1, min: 1 },
    COMMON_HW.H, COMMON_HW.L,
    { key: 'D', label: 'Depth', kind: 'number', default: 0, min: 0, unit: 'in' },
  ],
  compute: (inputs) => {
    const H = num(inputs, 'H');
    const L = num(inputs, 'L');
    const qty = Math.max(1, Math.round(num(inputs, 'qty', 1)));
    const D = num(inputs, 'D');
    const shape = str(inputs, 'shape', 'Rectangular');
    const extraColors = Math.max(0, Math.round(num(inputs, 'extraColors', 0)));
    const sqft = (H * L / 144) * qty;
    const perimeterFt = (((H + L) * 2) / 12) * qty;
    const fillerSqft = (D / 12) * perimeterFt;
    const paintArea = sqft + fillerSqft;
    const fabRateBase = tierFor(TABLES.polecover, sqft);
    const largePoleMul = L >= RATES.largePoleCoverFrameMultiplierSize ? RATES.largePoleCoverFrameMultiplier : 1;
    const fabHours = laborHours(sqft, fabRateBase) * largePoleMul;
    const radiusHours = shape === 'Radius/Angle' ? fabHours * RATES.radiusOrAngleExtraLaborPct : 0;
    const labor: ComputedLaborLine[] = [
      { workCode: 2011, description: 'Cabinet Metal Labor', hours: fabHours },
      { workCode: 2110, description: 'Paint Prep Labor', hours: laborHours(paintArea, RATES.cabinetPaintPrepSqftPerHour) },
      { workCode: 2112, description: 'Paint Cabinet & Letters Labor', hours: laborHours(paintArea, RATES.cabinetPaintSqftPerHour) },
    ];
    if (radiusHours > 0) labor.push({ workCode: 2011, description: 'Radius/Angle uplift', hours: radiusHours });
    if (extraColors > 0 && paintArea > 0) labor.push({ workCode: 2110, description: 'Extra color masking', hours: extraColors });
    const materials: ComputedMaterialLine[] = [];
    const paint = extraPaintMaterial(extraColors, paintArea);
    if (paint) materials.push(paint);
    return { sqft, labor, materials };
  },
};

const EMC_ASSEMBLY: PieceTypeDef = {
  id: 'emc-assembly',
  label: 'EMC assembly',
  workbookSheet: 'EMC assembly',
  status: 'implemented',
  references: ['TABLES.EMC; emcHandPaintSqftPerHour 20'],
  inputs: [
    COMMON_HW.H, COMMON_HW.L, COMMON_HW.qty,
    { key: 'pitch', label: 'Pixel pitch', kind: 'number', default: 0, min: 0, unit: 'mm', help: 'Informational only — assembly labor uses sqft.' },
  ],
  compute: (inputs) => {
    const H = num(inputs, 'H');
    const L = num(inputs, 'L');
    const qty = Math.max(1, Math.round(num(inputs, 'qty', 1)));
    const sqft = (H * L / 144) * qty;
    const fabRate = tierFor(TABLES.EMC, sqft);
    return {
      sqft,
      labor: [
        { workCode: 2215, description: 'EMC Assembly Labor', hours: laborHours(sqft, fabRate) },
        { workCode: 2116, description: 'EMC hand paint', hours: laborHours(sqft, RATES.emcHandPaintSqftPerHour) },
      ],
      materials: [],
    };
  },
};

// ---------------------------------------------------------------------------
// Registry
// ---------------------------------------------------------------------------

export const PIECE_TYPES: readonly PieceTypeDef[] = Object.freeze([
  FREEFORM_TM,
  APPLY_VINYL_GRAPHICS,
  VINYL_CUTTING,
  PAINT_CALCULATION,
  ROUTED_PANEL_SHAPES,
  ALUM_PAN_SIGN,
  ECONOMY_PAN_SIGN,
  POST_AND_PANEL,
  FLAT_PANELS_ONLY,
  ROUTED_FACE_ONLY,
  ROUTED_ALUM_FACES_LETTERS,
  ROUTED_PUSH_THROUGH_ACRYLIC,
  SF_ROUTED_CABINET,
  DF_ROUTED_CABINET,
  SF_ACRYLIC_CABINET,
  ECONOMY_SF_ACRYLIC,
  DF_ACRYLIC_CABINET,
  SF_FLEX_CABINET,
  DF_FLEX_CABINET,
  POLE_COVER,
  STRUCTURAL_STEEL_FAB,
  REVEAL,
  CROWN_COVE,
  EMC_ASSEMBLY,
  CRATING,
  LED_WIRING,
  CHANGEABLE_COPY_FACE,
  FLEX_FACE_ASSEMBLY,
  ROUTED_FACE_ASSEMBLY,
  TRIMCAP_LETTER_FACE,
  CHANNEL_LETTER_FABRICATION,
]);

export const PIECE_TYPE_BY_ID: ReadonlyMap<string, PieceTypeDef> = new Map(
  PIECE_TYPES.map(t => [t.id, t])
);

export function getPieceType(id: string): PieceTypeDef | undefined {
  return PIECE_TYPE_BY_ID.get(id);
}

export { tierFor, type RateTier, TABLES, RATES };
