"""Assemble an importable UNMANAGED solution (BCJobSketches) containing the
BCSync_JobSketches flow (generated by _gen_jobsketches_flow.py - run that first).

It reuses the Dataverse connection reference the other BCSync flows use
(new_sharedcommondataserviceforapps_4a52d) and adds a SharePoint one
(lum_sharedsharepointonline_jobsketches): on import, pick your SharePoint
connection for it (or create one, signed in as you).

Run from the flows/ folder:  python _build_neworders_solution.py

The flow imports OFF. Turn it on after import (see BCSync_JobSketches.md).
"""
import json
import os
import shutil
import zipfile

FLOWS   = os.path.dirname(os.path.abspath(__file__))
STAGE   = r"C:\Users\Alex\Downloads\bcjobsketches_build"
# ONLY_JOB=J38740 builds a test copy that runs for that one job only (the flow
# designer doesn't show flow parameters, so it's set here instead).
ONLY_JOB = os.environ.get("ONLY_JOB", "").strip()
VERSION  = "1.0.0.13" if ONLY_JOB else "1.0.0.14"
OUT_ZIP  = (rf"C:\Users\Alex\Downloads\BCJobSketches_TEST_{ONLY_JOB}.zip" if ONLY_JOB
            else rf"C:\Users\Alex\Downloads\BCJobSketches_{VERSION.replace('.', '_')}.zip")

FLOW_NAME    = "BCSync_JobSketches"
FLOW_GUID    = "50b2d0d0-2373-4c57-b756-2baaa335efda"
SRC_JSON     = "BCSync_JobSketches-clientdata.json"
DEST_JSON    = f"{FLOW_NAME}-{FLOW_GUID.upper()}.json"
DESC = ("Nightly: finds each open job's sketch in its SharePoint folder and saves its "
        "link and a thumbnail for the Jobs list Sketch column.")

workflow_block = f'''<Workflow WorkflowId="{{{FLOW_GUID}}}" Name="{FLOW_NAME}" Description="{DESC}">
      <JsonFileName>/Workflows/{DEST_JSON}</JsonFileName>
      <Type>1</Type>
      <Subprocess>0</Subprocess>
      <Category>5</Category>
      <Mode>0</Mode>
      <Scope>4</Scope>
      <OnDemand>0</OnDemand>
      <TriggerOnCreate>0</TriggerOnCreate>
      <TriggerOnDelete>0</TriggerOnDelete>
      <AsyncAutodelete>0</AsyncAutodelete>
      <SyncWorkflowLogOnFailure>0</SyncWorkflowLogOnFailure>
      <StateCode>0</StateCode>
      <StatusCode>1</StatusCode>
      <RunAs>1</RunAs>
      <IsTransacted>1</IsTransacted>
      <IntroducedVersion>1.0</IntroducedVersion>
      <IsCustomizable>1</IsCustomizable>
      <BusinessProcessType>0</BusinessProcessType>
      <IsCustomProcessingStepAllowedForOtherPublishers>1</IsCustomProcessingStepAllowedForOtherPublishers>
      <ModernFlowType>0</ModernFlowType>
      <PrimaryEntity>none</PrimaryEntity>
      <LocalizedNames>
        <LocalizedName languagecode="1033" description="{FLOW_NAME}" />
      </LocalizedNames>
      <Descriptions>
        <Description languagecode="1033" description="{DESC}" />
      </Descriptions>
    </Workflow>'''

conn_xml = '''<connectionreferences>
    <connectionreference connectionreferencelogicalname="lum_sharedsharepointonline_jobsketches">
      <connectionreferencedisplayname>SharePoint (Job Sketches)</connectionreferencedisplayname>
      <connectorid>/providers/Microsoft.PowerApps/apis/shared_sharepointonline</connectorid>
      <iscustomizable>1</iscustomizable>
      <statecode>0</statecode>
      <statuscode>1</statuscode>
    </connectionreference>
    <connectionreference connectionreferencelogicalname="new_sharedcommondataserviceforapps_4a52d">
      <connectionreferencedisplayname>Microsoft Dataverse</connectionreferencedisplayname>
      <connectorid>/providers/Microsoft.PowerApps/apis/shared_commondataserviceforapps</connectorid>
      <iscustomizable>1</iscustomizable>
      <statecode>0</statecode>
      <statuscode>1</statuscode>
    </connectionreference>
  </connectionreferences>'''

customizations = f'''<?xml version="1.0" encoding="utf-8"?>
<ImportExportXml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Entities />
  <Roles />
  <Workflows>
    {workflow_block}
  </Workflows>
  <FieldSecurityProfiles />
  <Templates />
  <EntityMaps />
  <EntityRelationships />
  <OrganizationSettings />
  <optionsets />
  <CustomControls />
  <EntityDataProviders />
  {conn_xml}
  <Languages>
    <Language>1033</Language>
  </Languages>
</ImportExportXml>
'''

solution = f'''<?xml version="1.0" encoding="utf-8"?>
<ImportExportXml version="9.2.26061.153" SolutionPackageVersion="9.2" languagecode="1033" generatedBy="CrmLive" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <SolutionManifest>
    <UniqueName>BCJobSketches</UniqueName>
    <LocalizedNames>
      <LocalizedName description="BC Job Sketches" languagecode="1033" />
    </LocalizedNames>
    <Descriptions />
    <Version>{VERSION}</Version>
    <Managed>0</Managed>
    <Publisher>
      <UniqueName>LumineoSigns</UniqueName>
      <LocalizedNames>
        <LocalizedName description="Lumineo Signs" languagecode="1033" />
      </LocalizedNames>
      <Descriptions />
      <EMailAddress xsi:nil="true"></EMailAddress>
      <SupportingWebsiteUrl xsi:nil="true"></SupportingWebsiteUrl>
      <CustomizationPrefix>lum</CustomizationPrefix>
      <CustomizationOptionValuePrefix>20000</CustomizationOptionValuePrefix>
      <Addresses />
    </Publisher>
    <RootComponents>
      <RootComponent type="29" id="{{{FLOW_GUID}}}" behavior="0" />
    </RootComponents>
    <MissingDependencies />
  </SolutionManifest>
</ImportExportXml>
'''

content_types = ('<?xml version="1.0" encoding="utf-8"?>'
                 '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
                 '<Default Extension="xml" ContentType="application/octet-stream" />'
                 '<Default Extension="json" ContentType="application/octet-stream" /></Types>')

with open(os.path.join(FLOWS, SRC_JSON), encoding="utf-8") as fh:
    doc = json.load(fh)
doc["properties"]["definition"]["parameters"]["Only_Job"]["defaultValue"] = ONLY_JOB

if os.path.exists(STAGE):
    shutil.rmtree(STAGE)
os.makedirs(os.path.join(STAGE, "Workflows"))
open(os.path.join(STAGE, "solution.xml"), "w", encoding="utf-8").write(solution)
open(os.path.join(STAGE, "customizations.xml"), "w", encoding="utf-8").write(customizations)
open(os.path.join(STAGE, "[Content_Types].xml"), "w", encoding="utf-8").write(content_types)
with open(os.path.join(STAGE, "Workflows", DEST_JSON), "w", encoding="utf-8") as fh:
    json.dump(doc, fh, indent=2)

if os.path.exists(OUT_ZIP):
    os.remove(OUT_ZIP)
with zipfile.ZipFile(OUT_ZIP, "w", zipfile.ZIP_DEFLATED) as z:
    for root, _, files in os.walk(STAGE):
        for f in files:
            full = os.path.join(root, f)
            z.write(full, os.path.relpath(full, STAGE).replace("\\", "/"))
shutil.rmtree(STAGE)

print("Built", OUT_ZIP, f"(Only_Job = {ONLY_JOB})" if ONLY_JOB else "(all jobs)")
with zipfile.ZipFile(OUT_ZIP) as z:
    for n in z.namelist():
        print("  ", n)
