"""Assemble an importable UNMANAGED solution (BCJobDescriptions) containing the
BCSync_JobDescriptions flow (generated by _gen_jobdesc_flow.py - run that first).

It reuses the SAME Dataverse connection reference the other BCSync flows use
(new_sharedcommondataserviceforapps_4a52d), so on import it binds to your
existing connection - no new connection. BC is read over HTTP (no connector).

Run from the flows/ folder:  python _build_jobdesc_solution.py

THE SECRET NEVER LIVES IN THE REPO. The flow calls our BC web service with the
app registration, like BCPush_PlanningSteps. Set it in the environment just for
the build:
    PowerShell:  $env:BC_CLIENT_SECRET="<secret>"; python _build_jobdesc_solution.py
It is injected into the STAGED copy only, and the zip is written to Downloads -
outside the repo - so a secret-bearing zip can't be committed. Without the env
var the build leaves the placeholder; fill Bc_ClientSecret in the flow editor.

The flow imports OFF. Turn it on after import (see BCSync_JobDescriptions.md).
"""
import json
import os
import shutil
import zipfile

FLOWS   = os.path.dirname(os.path.abspath(__file__))
STAGE   = r"C:\Users\Alex\Downloads\bcjobdesc_build"
OUT_ZIP = r"C:\Users\Alex\Downloads\BCJobDescriptions_1_0_0_2.zip"

FLOW_NAME    = "BCSync_JobDescriptions"
FLOW_GUID    = "d8b49661-ae47-4d70-ab6a-b585509d97ba"
SRC_JSON     = "BCSync_JobDescriptions-clientdata.json"
DEST_JSON    = f"{FLOW_NAME}-{FLOW_GUID.upper()}.json"
BC_CLIENT_ID = "34a4de23-4db0-48d9-a941-285c9c2f9b5d"
DESC = ("Hourly: each open job's Field / Production / Extended Description from BC "
        "into crfdf_jobdesc for the job panel's description sections.")

workflow_block = f'''<Workflow WorkflowId="{{{FLOW_GUID}}}" Name="{FLOW_NAME}" Description="{DESC}">
      <JsonFileName>/Workflows/{DEST_JSON}</JsonFileName>
      <Type>1</Type>
      <Subprocess>0</Subprocess>
      <Category>5</Category>
      <Mode>0</Mode>
      <Scope>4</Scope>
      <OnDemand>0</OnDemand>
      <TriggerOnCreate>0</TriggerOnCreate>
      <TriggerOnDelete>0</TriggerOnDelete>
      <AsyncAutodelete>0</AsyncAutodelete>
      <SyncWorkflowLogOnFailure>0</SyncWorkflowLogOnFailure>
      <StateCode>0</StateCode>
      <StatusCode>1</StatusCode>
      <RunAs>1</RunAs>
      <IsTransacted>1</IsTransacted>
      <IntroducedVersion>1.0</IntroducedVersion>
      <IsCustomizable>1</IsCustomizable>
      <BusinessProcessType>0</BusinessProcessType>
      <IsCustomProcessingStepAllowedForOtherPublishers>1</IsCustomProcessingStepAllowedForOtherPublishers>
      <ModernFlowType>0</ModernFlowType>
      <PrimaryEntity>none</PrimaryEntity>
      <LocalizedNames>
        <LocalizedName languagecode="1033" description="{FLOW_NAME}" />
      </LocalizedNames>
      <Descriptions>
        <Description languagecode="1033" description="{DESC}" />
      </Descriptions>
    </Workflow>'''

conn_xml = '''<connectionreferences>
    <connectionreference connectionreferencelogicalname="new_sharedcommondataserviceforapps_4a52d">
      <connectionreferencedisplayname>Microsoft Dataverse</connectionreferencedisplayname>
      <connectorid>/providers/Microsoft.PowerApps/apis/shared_commondataserviceforapps</connectorid>
      <iscustomizable>1</iscustomizable>
      <statecode>0</statecode>
      <statuscode>1</statuscode>
    </connectionreference>
  </connectionreferences>'''

customizations = f'''<?xml version="1.0" encoding="utf-8"?>
<ImportExportXml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Entities />
  <Roles />
  <Workflows>
    {workflow_block}
  </Workflows>
  <FieldSecurityProfiles />
  <Templates />
  <EntityMaps />
  <EntityRelationships />
  <OrganizationSettings />
  <optionsets />
  <CustomControls />
  <EntityDataProviders />
  {conn_xml}
  <Languages>
    <Language>1033</Language>
  </Languages>
</ImportExportXml>
'''

solution = f'''<?xml version="1.0" encoding="utf-8"?>
<ImportExportXml version="9.2.26061.153" SolutionPackageVersion="9.2" languagecode="1033" generatedBy="CrmLive" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <SolutionManifest>
    <UniqueName>BCJobDescriptions</UniqueName>
    <LocalizedNames>
      <LocalizedName description="BC Job Descriptions" languagecode="1033" />
    </LocalizedNames>
    <Descriptions />
    <Version>1.0.0.2</Version>
    <Managed>0</Managed>
    <Publisher>
      <UniqueName>LumineoSigns</UniqueName>
      <LocalizedNames>
        <LocalizedName description="Lumineo Signs" languagecode="1033" />
      </LocalizedNames>
      <Descriptions />
      <EMailAddress xsi:nil="true"></EMailAddress>
      <SupportingWebsiteUrl xsi:nil="true"></SupportingWebsiteUrl>
      <CustomizationPrefix>lum</CustomizationPrefix>
      <CustomizationOptionValuePrefix>20000</CustomizationOptionValuePrefix>
      <Addresses />
    </Publisher>
    <RootComponents>
      <RootComponent type="29" id="{{{FLOW_GUID}}}" behavior="0" />
    </RootComponents>
    <MissingDependencies />
  </SolutionManifest>
</ImportExportXml>
'''

content_types = ('<?xml version="1.0" encoding="utf-8"?>'
                 '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
                 '<Default Extension="xml" ContentType="application/octet-stream" />'
                 '<Default Extension="json" ContentType="application/octet-stream" /></Types>')

with open(os.path.join(FLOWS, SRC_JSON), encoding="utf-8") as fh:
    doc = json.load(fh)
params = doc["properties"]["definition"]["parameters"]
params["Bc_ClientId"]["defaultValue"] = BC_CLIENT_ID
secret = os.environ.get("BC_CLIENT_SECRET") or None
if secret:
    params["Bc_ClientSecret"]["defaultValue"] = secret

if os.path.exists(STAGE):
    shutil.rmtree(STAGE)
os.makedirs(os.path.join(STAGE, "Workflows"))
open(os.path.join(STAGE, "solution.xml"), "w", encoding="utf-8").write(solution)
open(os.path.join(STAGE, "customizations.xml"), "w", encoding="utf-8").write(customizations)
open(os.path.join(STAGE, "[Content_Types].xml"), "w", encoding="utf-8").write(content_types)
with open(os.path.join(STAGE, "Workflows", DEST_JSON), "w", encoding="utf-8") as fh:
    json.dump(doc, fh, indent=2)

if os.path.exists(OUT_ZIP):
    os.remove(OUT_ZIP)
with zipfile.ZipFile(OUT_ZIP, "w", zipfile.ZIP_DEFLATED) as z:
    for root, _, files in os.walk(STAGE):
        for f in files:
            full = os.path.join(root, f)
            z.write(full, os.path.relpath(full, STAGE).replace("\\", "/"))
shutil.rmtree(STAGE)  # the staged copy may hold the secret

print("Built", OUT_ZIP, "(secret injected)" if secret else "(secret NOT set - fill Bc_ClientSecret after import)")
with zipfile.ZipFile(OUT_ZIP) as z:
    for n in z.namelist():
        print("  ", n)
