"""Assemble an importable UNMANAGED solution (BCPoReceiving) containing the
BCPush_PoReceipts and BCPush_PoDeliveries flows (generated by
_gen_poreceiving_flows.py - run that first).

It reuses the SAME Dataverse connection reference the other BC flows use
(new_sharedcommondataserviceforapps_4a52d), so on import it binds to your
existing connection - no new connection. BC is written over HTTP (no connector).

Run from the flows/ folder:  python _build_poreceiving_solution.py

THE SECRET NEVER LIVES IN THE REPO. Both flows call our BC API pages with the
app registration, like BCSync_TaskCompletions. Set it in the environment just
for the build:
    PowerShell:  $env:BC_CLIENT_SECRET="<secret>"; python _build_poreceiving_solution.py
It is injected into the STAGED copy only, and the zip is written to Downloads -
outside the repo - so a secret-bearing zip can't be committed. Without the env
var the build leaves the placeholder; after import run
scripts/copy-bc-secret-to-flows.ps1 (the designer doesn't show definition
parameters, so there's nowhere to paste it).

The flows import OFF. Publish BC ext v1.0.0.18 first, then turn them on (see
BCPush_PoReceiving.md).
"""
import json
import os
import shutil
import zipfile

FLOWS   = os.path.dirname(os.path.abspath(__file__))
STAGE   = r"C:\Users\Alex\Downloads\bcporeceiving_build"
OUT_ZIP = r"C:\Users\Alex\Downloads\BCPoReceiving_1_0_0_2.zip"
BC_CLIENT_ID = "34a4de23-4db0-48d9-a941-285c9c2f9b5d"

FLOWS_IN = [
    ("BCPush_PoReceipts", "60995ffd-2bb4-43f3-b2e6-f82c0ed2b139",
     "A PO's Vendor Status from the Switchboard app's Warehouse Management into BC "
     "(Purchase Order card and Job Card)."),
    ("BCPush_PoDeliveries", "cd266c02-9c03-4cba-9425-03704ac2054e",
     "Deliveries received against POs in the Switchboard app's Warehouse Management "
     "into BC - added, edited and removed (Purchase Order card and Job Card)."),
]


def workflow_block(name, guid, desc):
    return f'''<Workflow WorkflowId="{{{guid}}}" Name="{name}" Description="{desc}">
      <JsonFileName>/Workflows/{name}-{guid.upper()}.json</JsonFileName>
      <Type>1</Type>
      <Subprocess>0</Subprocess>
      <Category>5</Category>
      <Mode>0</Mode>
      <Scope>4</Scope>
      <OnDemand>0</OnDemand>
      <TriggerOnCreate>0</TriggerOnCreate>
      <TriggerOnDelete>0</TriggerOnDelete>
      <AsyncAutodelete>0</AsyncAutodelete>
      <SyncWorkflowLogOnFailure>0</SyncWorkflowLogOnFailure>
      <StateCode>0</StateCode>
      <StatusCode>1</StatusCode>
      <RunAs>1</RunAs>
      <IsTransacted>1</IsTransacted>
      <IntroducedVersion>1.0</IntroducedVersion>
      <IsCustomizable>1</IsCustomizable>
      <BusinessProcessType>0</BusinessProcessType>
      <IsCustomProcessingStepAllowedForOtherPublishers>1</IsCustomProcessingStepAllowedForOtherPublishers>
      <ModernFlowType>0</ModernFlowType>
      <PrimaryEntity>none</PrimaryEntity>
      <LocalizedNames>
        <LocalizedName languagecode="1033" description="{name}" />
      </LocalizedNames>
      <Descriptions>
        <Description languagecode="1033" description="{desc}" />
      </Descriptions>
    </Workflow>'''


conn_xml = '''<connectionreferences>
    <connectionreference connectionreferencelogicalname="new_sharedcommondataserviceforapps_4a52d">
      <connectionreferencedisplayname>Microsoft Dataverse</connectionreferencedisplayname>
      <connectorid>/providers/Microsoft.PowerApps/apis/shared_commondataserviceforapps</connectorid>
      <iscustomizable>1</iscustomizable>
      <statecode>0</statecode>
      <statuscode>1</statuscode>
    </connectionreference>
  </connectionreferences>'''

workflows = "\n    ".join(workflow_block(*f) for f in FLOWS_IN)
customizations = f'''<?xml version="1.0" encoding="utf-8"?>
<ImportExportXml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Entities />
  <Roles />
  <Workflows>
    {workflows}
  </Workflows>
  <FieldSecurityProfiles />
  <Templates />
  <EntityMaps />
  <EntityRelationships />
  <OrganizationSettings />
  <optionsets />
  <CustomControls />
  <EntityDataProviders />
  {conn_xml}
  <Languages>
    <Language>1033</Language>
  </Languages>
</ImportExportXml>
'''

roots = "\n      ".join(f'<RootComponent type="29" id="{{{g}}}" behavior="0" />' for _, g, _ in FLOWS_IN)
solution = f'''<?xml version="1.0" encoding="utf-8"?>
<ImportExportXml version="9.2.26061.153" SolutionPackageVersion="9.2" languagecode="1033" generatedBy="CrmLive" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <SolutionManifest>
    <UniqueName>BCPoReceiving</UniqueName>
    <LocalizedNames>
      <LocalizedName description="BC PO Receiving" languagecode="1033" />
    </LocalizedNames>
    <Descriptions />
    <Version>1.0.0.2</Version>
    <Managed>0</Managed>
    <Publisher>
      <UniqueName>LumineoSigns</UniqueName>
      <LocalizedNames>
        <LocalizedName description="Lumineo Signs" languagecode="1033" />
      </LocalizedNames>
      <Descriptions />
      <EMailAddress xsi:nil="true"></EMailAddress>
      <SupportingWebsiteUrl xsi:nil="true"></SupportingWebsiteUrl>
      <CustomizationPrefix>lum</CustomizationPrefix>
      <CustomizationOptionValuePrefix>20000</CustomizationOptionValuePrefix>
      <Addresses />
    </Publisher>
    <RootComponents>
      {roots}
    </RootComponents>
    <MissingDependencies />
  </SolutionManifest>
</ImportExportXml>
'''

content_types = ('<?xml version="1.0" encoding="utf-8"?>'
                 '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
                 '<Default Extension="xml" ContentType="application/octet-stream" />'
                 '<Default Extension="json" ContentType="application/octet-stream" /></Types>')

secret = os.environ.get("BC_CLIENT_SECRET") or None

if os.path.exists(STAGE):
    shutil.rmtree(STAGE)
os.makedirs(os.path.join(STAGE, "Workflows"))
open(os.path.join(STAGE, "solution.xml"), "w", encoding="utf-8").write(solution)
open(os.path.join(STAGE, "customizations.xml"), "w", encoding="utf-8").write(customizations)
open(os.path.join(STAGE, "[Content_Types].xml"), "w", encoding="utf-8").write(content_types)
for name, guid, _ in FLOWS_IN:
    with open(os.path.join(FLOWS, f"{name}-clientdata.json"), encoding="utf-8") as fh:
        doc = json.load(fh)
    params = doc["properties"]["definition"]["parameters"]
    params["Bc_ClientId"]["defaultValue"] = BC_CLIENT_ID
    if secret:
        params["Bc_ClientSecret"]["defaultValue"] = secret
    with open(os.path.join(STAGE, "Workflows", f"{name}-{guid.upper()}.json"), "w", encoding="utf-8") as fh:
        json.dump(doc, fh, indent=2)

if os.path.exists(OUT_ZIP):
    os.remove(OUT_ZIP)
with zipfile.ZipFile(OUT_ZIP, "w", zipfile.ZIP_DEFLATED) as z:
    for root, _, files in os.walk(STAGE):
        for f in files:
            full = os.path.join(root, f)
            z.write(full, os.path.relpath(full, STAGE).replace("\\", "/"))
shutil.rmtree(STAGE)  # the staged copy may hold the secret

print("Built", OUT_ZIP, "(secret injected)" if secret else "(secret NOT set - after import run scripts/copy-bc-secret-to-flows.ps1)")
with zipfile.ZipFile(OUT_ZIP) as z:
    for n in z.namelist():
        print("  ", n)
