"""Generate BCSync_TaskCompletions-clientdata.json.

BCSync_TaskCompletions copies the shop floor's "Task complete" ticks from BC
into Dataverse (crfdf_taskcompletion, state "pending"). The ticks are made on
Infotech's Clock In Job / Clock Out Job pages through our extension
(bc/lumineo-planning-ext v1.0.0.12+: table 58410, API page 58411
api/lumineo/planning/v1.0/.../taskCompletions). The Project Scheduler app then
completes each one's department on the job's stepper and moves the job's
Current Status (store/task-completion-processor.ts).

Every 5 minutes, one run at a time:
  1. the highest BC Entry No. already copied (crfdf_entryno, 0 when none);
  2. BC taskCompletions with entryNo above it, oldest first;
  3. one crfdf_taskcompletion row each, state "pending".
Entry numbers only grow, so a row is never copied twice and a missed run is
caught up by the next.

The expressions are quote-heavy, so the JSON is GENERATED - edit here:

    python _gen_taskcompletions_flow.py

then build the solution with _build_taskcompletions_solution.py. See
BCSync_TaskCompletions.md.
"""
import json
import os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "BCSync_TaskCompletions-clientdata.json")

DV = {"apiId": "/providers/Microsoft.PowerApps/apis/shared_commondataserviceforapps",
      "connectionName": "shared_commondataserviceforapps"}
AUTH = {"type": "ActiveDirectoryOAuth", "authority": "https://login.microsoftonline.com",
        "tenant": "@parameters('Bc_Tenant')", "audience": "@parameters('Bc_Audience')",
        "clientId": "@parameters('Bc_ClientId')", "secret": "@parameters('Bc_ClientSecret')"}
API = "@{parameters('Bc_ApiBase')}/lumineo/planning/v1.0/companies(@{parameters('Bc_CompanyId')})"
SET = "crfdf_taskcompletions"
ROW = "items('For_each_completion')"


def after(*names):
    return {n: ["Succeeded"] for n in names}


def dv(op, params, run_after=None):
    return {"type": "OpenApiConnection", "runAfter": run_after or {},
            "inputs": {"parameters": params, "host": {**DV, "operationId": op}}}


def col(name):
    return f"@coalesce({ROW}?['{name}'], '')"


actions = {
    "Last_Copied": dv("ListRecords", {"entityName": SET, "$select": "crfdf_entryno",
                                      "$orderby": "crfdf_entryno desc", "$top": 1}),
    "Since_Entry": {"type": "Compose", "runAfter": after("Last_Copied"),
                    "inputs": "@coalesce(first(body('Last_Copied')?['value'])?['crfdf_entryno'], 0)"},
    "Get_New_Completions": {
        "type": "Http", "runAfter": after("Since_Entry"),
        "inputs": {"method": "GET",
                   "uri": (f"{API}/taskCompletions?$filter=@{{encodeUriComponent(concat('entryNo gt ', "
                           "string(outputs('Since_Entry'))))}&$orderby=entryNo"),
                   "headers": {"Accept": "application/json"}, "authentication": AUTH}},
    "For_each_completion": {
        "type": "Foreach", "foreach": "@body('Get_New_Completions')?['value']", "runAfter": after("Get_New_Completions"),
        # In entry order, one at a time: Last_Copied relies on every lower entry being in.
        "runtimeConfiguration": {"concurrency": {"repetitions": 1}},
        "actions": {"Add_Pending": dv("CreateRecord", {
            "entityName": SET,
            "item/crfdf_name": f"@concat('BC ', string({ROW}?['entryNo']))",
            "item/crfdf_entryno": f"@{ROW}?['entryNo']",
            "item/crfdf_jobno": col("jobNo"),
            "item/crfdf_jobtaskno": col("jobTaskNo"),
            "item/crfdf_taskdesc": col("jobTaskDescription"),
            "item/crfdf_resourceno": col("resourceNo"),
            "item/crfdf_resourcename": col("resourceName"),
            "item/crfdf_completedat": col("completedAt"),
            "item/crfdf_source": col("source"),
            "item/crfdf_state": "pending",
        })}},
}

flow = {
    "properties": {
        "connectionReferences": {
            "shared_commondataserviceforapps": {
                "api": {"name": "shared_commondataserviceforapps"},
                "connection": {"connectionReferenceLogicalName": "new_sharedcommondataserviceforapps_4a52d"},
                "runtimeSource": "embedded"},
        },
        "definition": {
            "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
            "contentVersion": "1.0.0.0",
            "comment": ("BCSync_TaskCompletions - GENERATED by _gen_taskcompletions_flow.py; edit that, not this. "
                        "Every 5 min: the shop floor's Task complete ticks from BC into crfdf_taskcompletion "
                        "(pending) for the app to apply. See BCSync_TaskCompletions.md."),
            "parameters": {
                "$authentication": {"defaultValue": {}, "type": "SecureObject"},
                "$connections": {"defaultValue": {}, "type": "Object"},
                "Bc_ApiBase": {"type": "String", "defaultValue":
                               "https://api.businesscentral.dynamics.com/v2.0/fe0182fa-d183-46ab-8493-9e8ea9c3d0b8/UAT/api"},
                "Bc_CompanyId": {"type": "String", "defaultValue": "4738bfb5-a06d-ec11-bf27-000d3a132a9e"},
                "Bc_Tenant": {"type": "String", "defaultValue": "fe0182fa-d183-46ab-8493-9e8ea9c3d0b8"},
                "Bc_Audience": {"type": "String", "defaultValue": "https://api.businesscentral.dynamics.com"},
                "Bc_ClientId": {"type": "String", "defaultValue": "<< Postman app registration client id >>"},
                "Bc_ClientSecret": {"type": "String", "defaultValue": "<< store in Key Vault / secure env var - do NOT commit >>"},
            },
            "triggers": {"Every_5_minutes": {
                "type": "Recurrence",
                "recurrence": {"frequency": "Minute", "interval": 5},
                # One run at a time, so two runs can't copy the same entries.
                "runtimeConfiguration": {"concurrency": {"runs": 1}}}},
            "actions": actions,
        },
    },
    "schemaVersion": "1.0.0.0",
}

with open(OUT, "w", encoding="utf-8") as f:
    json.dump(flow, f, indent=2, ensure_ascii=False)
    f.write("\n")
print("wrote", OUT)
